### ISSUE TITLE
crash due to comments in en.yml

### ISSUE THREAD

**Issue by sesam** [unho/yaml2po#1]
Crashes because of the # in below sample:

``` yaml
en:
  activerecord:
    models:
      #
    attributes:
      ...
```

**Comment by unho** [comment]
This should be now fixed. Thanks a lot for reporting the bug.

Sorry for the delay. Ruby is not my preferred programming language and this is not one of my preferred projects.

**Comment by sesam** [comment]
Thanks! :)
